OnlineShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
                  path('', views.home, name='home'),
                  path('catalog/', views.catalog, name='catalog'),
                  path('catalog/goods/<int:item_id>', views.detail, name='details_product'),
                  path('catalog/goods/<int:item_id>/<int:size_id>', views.detail, name='details_product'),
                  path('favorite_products/', views.favorite_products, name='favorite_products'),
                  path('brands/', views.brands, name='brands'),
                  path('purchases/', views.list_purchases, name='list_purchases'),
                  path('purchases/<int:purchase_id>', views.purchase_detail, name='purchase_detail'),
                  path('brands/<int:company_id>', views.detail_company, name='company_detail'),
                  path('cart/', views.cart_detail, name='cart'),
                  path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
                  path('cart/add/<int:product_id>/<int:size_id>', views.cart_add, name='cart_addTrue'),
                  path('cart/remove/<int:product_id>/<int:size_id>/', views.cart_remove, name='cart_remove'),
                  path('catalog/goods/favorite_<int:item_id>', views.add_favorite, name='favorite_add'),
                  path('catalog/goods/favorite_remove_<int:item_id>', views.remove_favorite, name='remove_favorite'),
                  path('review/', views.add_review, name='review'),
                  path('reviewList/', views.list_reviews, name='review_list'),
                  path('review/remove/<int:review_id>', views.remove_review, name='remove_review'),
              ]

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.login_in, name='login_in'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('edit/', views.profile_edit, name='profile_edit'),
]

main/forms.py
from django import forms
import django_filters

from main.models import Category, Review, Product, GENDER_ID


class CartAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']


class ReviewFormImages(ReviewForm):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    product = forms.ModelChoiceField(queryset=Product.objects.all(), widget=forms.HiddenInput())

    class Meta(ReviewForm.Meta):
        fields = ReviewForm.Meta.fields + ['images']


class ProductFilterSet(django_filters.FilterSet):
    category = django_filters.ModelMultipleChoiceFilter(queryset=Category.objects.all(),
                                                        widget=forms.CheckboxSelectMultiple)
    min_price = django_filters.NumberFilter(field_name='price', lookup_expr='gte')
    max_price = django_filters.NumberFilter(field_name='price', lookup_expr='lte')

    order_by = django_filters.OrderingFilter(
        choices=(
            ('price', 'По возрастанию'),
            ('-price', 'По убыванию'),
            ('-release', 'От новых к старым'),
            ('release', 'От старых к новым'),
        ),
        fields=(
            ('price', 'price'),
            ('release', 'release'),
        ),
        widget=forms.RadioSelect,
    )

    class Meta:
        model = Product
        fields = ['category', 'min_price', 'max_price', 'gender']

class ReviewFilterSet(django_filters.FilterSet):
    order_by = django_filters.OrderingFilter(
        choices=(
            ('rating', 'Сначала отрицательные отзывы'),
            ('-rating', 'Сначала положительные отзыва'),
            ('-created_at', 'Сначало новые'),
            ('created_at', 'Сначала старые'),
        ),
        fields=(
            ('rating', 'rating'),
            ('created_at', 'created_at')
        )
    )

main/views.py
from _decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST

from django.core.mail import send_mail

from OnlineShopProject import settings
from users.forms import PersonalInformation
from .cart import Cart
from .forms import CartAddProductForm, ReviewFormImages, ProductFilterSet
from .models import Product, Company, ProductSize, FavoriteList, Review, Purchase, ReviewPhotos


def home(request):
    recent_release = Product.objects.order_by('-release')[:5]
    return render(request, 'main/home.html', {
        'recent_release': recent_release
    })


def brands(request):
    brands_list = Company.objects.order_by('name_company')
    return render(request, 'main/brands.html', {
        'title': 'Бренды',
        'brands_list': brands_list,
    })


def catalog(request):
    products = Product.objects.all()
    filter_set = ProductFilterSet(request.GET, queryset=products)

    if 'price' in request.GET:
        direction = '-' if request.GET['price'] == 'desc' else ''
        filter_set.qs = filter_set.qs.order_by(direction + 'price')

    if 'release_date' in request.GET:
        direction = '-' if request.GET['release_date'] == 'desc' else ''
        filter_set.qs = filter_set.qs.order_by(direction + 'release_date')

    filtered_params = request.GET.copy()
    if 'page' in filtered_params:
        del filtered_params['page']
    filtered_query_string = filtered_params.urlencode()

    paginator = Paginator(filter_set.qs, per_page=6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.user.is_authenticated:
        if Purchase.objects.filter(user=request.user):
            sale = False
        else:
            sale = True
    else:
        sale = True

    context = {
        'filterset': filter_set,
        'page_obj': page_obj,
        'filtered_query_string': filtered_query_string,
        'sale_check': sale,
    }
    return render(request, 'main/catalog.html', context)


def detail(request, item_id, size_id=0):
    item = Product.objects.get(pk=item_id)
    sizes = ProductSize.objects.filter(product=item, quantity__gt=0).order_by('size')
    review_list = Review.objects.filter(product=item).order_by('-created_at')
    cart_product_form = CartAddProductForm()
    include_item = False
    purchases = None
    review = None

    if request.user.is_authenticated:
        purchases = Purchase.objects.filter(check_products__in=[item], user=request.user)
        is_favorite = FavoriteList.objects.get(user=request.user).products.all().filter(id=item_id)
        if is_favorite:
            include_item = True

    if purchases:
        review = ReviewFormImages(initial={'product': item})

    context = {
        'item': item,
        'sizes': sizes,
        'choiceSize': sizes.get(pk=size_id) if size_id != 0 else None,
        'cart_product_form': cart_product_form,
        'include_item': include_item,
        'review': review,
        'review_list': review_list,
    }
    return render(request, 'main/detailItem.html', context)


def detail_company(request, company_id):
    company = Company.objects.get(pk=company_id)
    products = Product.objects.filter(company_id=company.id)
    filterset = ProductFilterSet(request.GET, queryset=products)

    context = {
        'company': company,
        'produts': filterset.qs,
        'filterset': filterset,
    }
    return render(request, 'main/companyDetail.html', context)


@login_required(login_url='/users/login')
def favorite_products(request):
    favorite = FavoriteList.objects.get(user=request.user).get_all_products()
    return render(request, 'main/favoriteItems.html', {
        'favorite_products': favorite,
    })


@require_POST
@login_required(login_url='/users/login')
def cart_add(request, product_id, size_id):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    size = ProductSize.objects.filter(product=product).get(pk=size_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, size)
        messages.success(request, 'Товар успешно добавлен в корзину!')
    else:
        messages.success(request, 'Произошла ошибка!')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='/users/login')
def cart_remove(request, product_id, size_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    size = ProductSize.objects.get(pk=size_id)
    cart.remove(product, size)
    return redirect('main:cart')


@login_required(login_url='/users/login')
def cart_detail(request):
    cart = Cart(request)
    length_cart = len(cart.cart)
    if Purchase.objects.filter(user=request.user):
        total_price = cart.get_total_price()
    else:
        total_price = cart.get_total_price() * Decimal("0.90")

    if request.method == 'POST':
        form = PersonalInformation(request.POST, instance=request.user)
        if form.is_valid() and length_cart != 0:
            for field in form.cleaned_data:
                if not form.cleaned_data[field]:
                    form.add_error(field, 'Это поле обязательное')
                    return render(request, 'main/cart.html', {
                        'cart': cart,
                        'form': form,
                    })
            form.save()
            request.user.street = form.cleaned_data['street']
            request.user.city = form.cleaned_data['city']
            request.user.city = form.cleaned_data['postcode']
            request.user.phone_no = form.cleaned_data['phone_no']

            total_price = 0
            list_products = []

            for item in cart.cart.values():
                total_price += Decimal(item['price']) * Decimal(item['quantity'])
                product = Product.objects.get(id=item['id'])
                list_products.append(product)
                size = ProductSize.objects.get(product=product, size=item['size'])
                if size.quantity >= item['quantity']:
                    size.quantity -= item['quantity']
                else:
                    return render(request, 'main/cart.html', {
                        'cart': cart,
                        'form': form,
                        'alert': True,
                        'avalible': size.quantity,
                        'product_name': product.name_item,
                    })
                size.save()
            if not Purchase.objects.filter(user=request.user):
                total_price *= Decimal("0.90")
            print(total_price)
            Purchase.objects.create(user=request.user, total_price=total_price, street=request.user.street,
                                    city=request.user.city,
                                    products=cart.cart,
                                    postcode=request.user.postcode).check_products.set(list_products),

            # send_email_purches(subject='Покупка', message='Спасибо за покупку', userName=request.user,
            #                    products=products,
            #                    recipient_list=[request.user.email])
            cart.clear()
            # return redirect('main:cart')
            return render(request, 'main/cart.html', {
                'form': form,
                'purchases_compleate': True
            })
    else:
        form = PersonalInformation(instance=request.user)

    return render(request, 'main/cart.html', {
        'cart': cart,
        'form': form,
        'total_price': total_price,
        'length_cart': length_cart,
    })


@login_required(login_url='/users/login')
def add_favorite(request, item_id):
    product = Product.objects.get(id=item_id)
    favorite_list = FavoriteList.objects.get(user=request.user)
    favorite_list.products.add(product)
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='/users/login')
def remove_favorite(request, item_id):
    product = Product.objects.get(id=item_id)
    favorite_list = FavoriteList.objects.get(user=request.user)
    favorite_list.products.remove(product)
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='/users/login')
def add_review(request):
    if request.method == 'POST':
        form = ReviewFormImages(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('images')
        if form.is_valid():
            user = request.user
            comment = form.cleaned_data['comment']
            rating = form.cleaned_data['rating']
            product = form.cleaned_data['product']
            review_obj = Review.objects.create(user=user, comment=comment, rating=rating, product=product)
            for photo in files:
                print(photo)
                ReviewPhotos.objects.create(review=review_obj, images=photo)
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            form = ReviewFormImages()


def send_email_purches(subject, message, userName, products, recipient_list):
    html_message = render_to_string('message/message.html', {
        'subject': subject,
        'message': message,
        'user': userName,
        'products': products,
    })
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list, html_message=html_message)


def list_purchases(request):
    purchases = Purchase.objects.filter(user=request.user).order_by('-created_at')
    context = {
        'list_purchases': purchases
    }
    return render(request, 'main/listPurchases.html', context)


def purchase_detail(request, purchase_id):
    purchase = Purchase.objects.get(pk=purchase_id)
    list_products = []

templates/main/cart.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}

{% block content %}
    <h1 style="text-align: center; margin: 10px 0;">Корзина</h1>
    {% if alert %}
        <div>
            <p>Вы выбрали количество больше, чем есть на складе. На данный момент доступно
                только: {{ avalible }} {{ product_name }}</p>
        </div>
    {% endif %}
    {% if purchases_compleate %}
        <h2>Спасибо за покупку! Данные о покупке можно посмотреть в разделе "покупки"</h2>
    {% endif %}
    <table class="cart" style="margin: 0 auto">
        <thead>
        <tr>
            <th style="padding: 20px">Изображение</th>
            <th style="padding: 20px">Продукт</th>
            <th style="padding: 20px">Количество</th>
            <th style="padding: 20px">Удалить?</th>
            <th style="padding: 20px">Цена за 1 товар</th>
            <th style="padding: 20px">Размер</th>
            <th style="padding: 20px">Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr style="border: 1px solid gray">
                    <td style="padding: 0 20px">
                        <img src="{{ product.image_prev.url }}" alt="{{ item.name_item }}"
                             style="width: 200px; height: 200px; object-fit: cover;">
                    </td>
                    <td style="font-size: 20px; width: 200px; padding: 0 20px">{{ product.name_item }}</td>
                    <td style="padding: 0 20px">{{ item.quantity }}</td>
                    <td style="padding: 0 20px"><a
                            href="{% url "main:cart_remove" product.id item.size_id %}">Remove</a></td>
                    <td style="padding: 0 20px" class="num">{{ product.price }} руб.</td>
                    <td style="padding: 0 20px" class="num">{{ item.size.size }}</td>
                    <td style="padding: 0 20px" class="num">{{ item.total_price }} руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td colspan="4"></td>
            {% if cart.get_total_price != 0 %}
                <td class="num" style="padding: 0 20px">{{ total_price }} руб.</td>
            {% endif %}

        </tr>
        </tbody>
    </table>
    <div style="text-align: center">
        <div>
            {% if length_cart %}
                <form action="{% url 'main:cart' %}" method="post" class="personalInformation">
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-info" type="submit">Submit</button>
                </form>
            {% endif %}

        </div>
        <p class="text-right">
            <a href="{% url "main:catalog" %}" class="button light" style="margin-right: 10px;">Continue shopping</a>
        </p>
    </div>

{% endblock %}

templates/main/detailItem.html
{% extends 'main/layout.html' %}

{% block title %}{{ item.name_item }}{% endblock %}

{% block content %}
    <div class="wrapper-detail">
        <div class="left-menu detail_cover-img">
            <div>
                <img class="detail_mainImg" src="{{ item.image_prev.url }}" alt="">
            </div>
            {% for photo in item.get_all_photos %}
                <div>
                    <img class="detail_mainImg" src="{{ photo.images.url }}" alt="123">
                </div>
            {% endfor %}
        </div>
        <div class="right-menu">
            <div class="detail__text">
                <p class="detail__title">{{ item.company.name_company }}</p>
                <p class="detail__description">{{ item.name_item }}</p>
                {% if sizes %}
                    <button type="button" class="btn btn-dark" style="margin-bottom: 30px;" data-bs-toggle="modal"
                            data-bs-target="#exampleModal">
                        Выбрать размер
                    </button>
                {% else %}
                    <button disabled type="button" class="btn btn-dark" style="margin-bottom: 30px;"
                            data-bs-toggle="modal"
                            data-bs-target="#exampleModal">
                        Выбрать размер
                    </button>
                    <p>К сожалению, данного товара сейчас нет в наличии</p>
                {% endif %}

                <div>
                    {% if choiceSize %}
                        <form action="{% url 'main:cart_addTrue' product_id=item.id size_id=choiceSize.id %}"
                              method="post">
                            {% csrf_token %}
                            {{ cart_product_form }}
                            <button type="submit" class="btn btn-success">
                                Купить<br><span>размер: {{ choiceSize.size }}</span></button>
                        </form>
                    {% endif %}
                </div>


            </div>
            <div class="detail__price" style="padding-left: 10px;">
                <p class="detail__textPrice">{{ item.price }} руб.</p>
            </div>
            <div class="detail__list">
                <ul>
                    <li>
                        <div>
                            <span>Название</span>
                            <p>{{ item.name_item }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <span>Код товара</span>
                            <p>{{ item.id }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            {% if include_item %}
                                <a href="{% url "main:remove_favorite" item.id %}">Удалить из избраного</a>
                            {% else %}
                                <a href="{% url "main:favorite_add" item.id %}">Добавить в избранное</a>
                            {% endif %}

                        </div>
                    </li>
                    <li>
                        <div>
                            <p>Описание</p>
                        </div>
                    </li>
                    <li>
                        {% if request.user.is_authenticated %}
                            <button style="margin: 10px 0" type="button" class="btn btn-primary" data-bs-toggle="modal"
                                    data-bs-target="#createReviewModal">
                                Написать отзыв
                            </button>
                        {% else %}
                            <button disabled style="margin: 10px 0" type="button" class="btn btn-dark"
                                    data-bs-toggle="modal"
                                    data-bs-target="#createReviewModal">
                                Написать отзыв
                            </button>
                        {% endif %}

                    </li>
                    <li>
                        <button type="button" class="btn btn-dark" data-bs-toggle="modal"
                                data-bs-target="#reviewList">
                            Отзывы
                        </button>
                    </li>
                </ul>
            </div>
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        {% if item.category.type_product == 'S' %}
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Выберете размер обуви</h1>
                        {% elif item.category.type_product == 'O' %}
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Выберете размер одежды</h1>
                        {% endif %}

                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        {% for size in sizes %}
                            <a class="btn btn-dark"
                               href="{% url "main:details_product" item_id=item.id size_id=size.id %}">{{ size.size }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


        {% if messages %}
            {% for message in messages %}
                <div id="myModalReport" class="modal-report">
                    <div class="modal-content">
                        <span class="close">&times;</span>
                        <p>{{ message }}</p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="modal fade" id="createReviewModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                {% if request.user.is_authenticated %}
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Напишите свой отзыв</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        {% if review %}
                            <form action="{% url 'main:review' %}" method="post" class="note-form"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ review }}
                                <button type="submit">Сохранить</button>
                            </form>
                        {% else %}
                            <div>
                                <p>Вы не можете написать отзыв так как вы не покупали данный товар</p>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>



    <div class="modal fade" id="reviewList" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-reviewTitle fs-5" id="exampleModalLabel">Отзывы</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% if review_list %}
                        {% for review in review_list %}
                            <div class="review">
                                <div class="review-header">
                                    <p class="review-username">{{ review.user.username }}</p>
                                    <p class="review-rating">Оценка: {{ review.rating }}/5</p>
                                </div>

                                <div class="review-content">
                                    <div class="review-wrapperPhoto">
                                        {% for photo in review.get_all_photos %}
                                            <img src="{{ photo.images.url }}"
                                                 alt=""
                                                 class="review-photo"
                                            >
                                        {% endfor %}
                                    </div>
                                    <p>{{ review.comment }}</p>
                                    <p>{{ review.created_at }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>На данный момент, отзывы на этот товар отсутсвуют.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'main/scripts/jquery-3.6.4.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="wrapper-header">
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'main:home' %}">Онлайн магазин</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:catalog' %}">Каталог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:brands' %}" tabindex="-1"
                               aria-disabled="true">Бренды</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <div style="position: relative">
                                    <a class="nav-link" id="check-link" href="{% url 'main:list_purchases' %}">Покупки</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <div style="position: relative">
                                    <a class="nav-link" id="check-link" href="{% url 'main:favorite_products' %}">Избранные товары</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <div style="position: relative">
                                    <a class="nav-link" id="check-link" href="{% url 'main:cart' %}">Корзина</a>
                                </div>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:profile' %}" tabindex="-1"
                                   aria-disabled="true">Профиль</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login_in' %}" tabindex="-1"
                                   aria-disabled="true">Войти</a>
                            </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}

    {% endblock %}
</div>
<script type="text/javascript" src="{% static 'main/scripts/test.js' %}"></script>
</body>
</html>

templates/main/review.html
{% extends 'main/layout.html' %}

{% block title %}Review{% endblock %}

{% block content %}
    <h1>Отзывы</h1>
    {% for review in reviews %}
        <div class="review">
            <p>{{ review.user }} - {{ review.rating }}/5</p>
            <p>{{ review.comment }}</p>
            <p>{{ review.created_at }}</p>
        </div>
    {% endfor %}

    <h2>Оставить отзыв</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}