OnlineShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
                  path('', views.home, name='home'),
                  path('catalog/', views.catalog, name='catalog'),
                  path('catalog/goods/<int:item_id>', views.detail, name='details_product'),
                  path('catalog/goods/<int:item_id>/<int:size_id>', views.detail, name='details_product'),
                  path('favorite_products/', views.favorite_products, name='favorite_products'),
                  path('brands/', views.brands, name='brands'),
                  path('purchases/', views.list_purchases, name='list_purchases'),
                  path('purchases/<int:purchase_id>', views.purchase_detail, name='purchase_detail'),
                  path('brands/<int:company_id>', views.detail_company, name='company_detail'),
                  path('cart/', views.cart_detail, name='cart'),
                  path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
                  path('cart/add/<int:product_id>/<int:size_id>', views.cart_add, name='cart_addTrue'),
                  path('cart/remove/<int:product_id>/<int:size_id>/', views.cart_remove, name='cart_remove'),
                  path('catalog/goods/favorite_<int:item_id>', views.add_favorite, name='favorite_add'),
                  path('catalog/goods/favorite_remove_<int:item_id>', views.remove_favorite, name='remove_favorite'),
                  path('review/', views.add_review, name='review'),
                  path('reviewList/', views.list_reviews, name='review_list'),
                  path('review/remove/<int:review_id>', views.remove_review, name='remove_review'),
              ]

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.login_in, name='login_in'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('edit/', views.profile_edit, name='profile_edit'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, unique=True)

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.BooleanField(default=False)

    street = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)

    email = models.EmailField(max_length=100, unique=False, blank=True)
    phone_no = models.CharField(max_length=10, unique=False, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput, EmailInput

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'phone_no')
        widgets = {
            'username': TextInput(attrs={
                'class': 'login__username',
            }),
            'email': EmailInput(attrs={
                'class': 'login__email',
            }),
            'phone_no': TextInput(attrs={
                'class': 'login__phone'
            })
        }


class UserEdit(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'phone_no')
        widgets = {
            'first_name': TextInput(attrs={
                'class': "person-input",
            }),
            'last_name': TextInput(attrs={
                'class': 'person-input',
            }),
            'email': EmailInput(attrs={
                'class': "person-input",
                'style': 'width: 480px;'
            }),
            'phone_no': TextInput(attrs={
                'class': 'person-input',
                'style': 'width: 480px;'
            })
        }


class PersonalInformation(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'city', 'street', 'postcode', 'phone_no']
        required = ['first_name', 'last_name', 'city', 'street', 'postcode', 'phone_no']

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from main.models import FavoriteList
from users.forms import CustomUserCreationForm, UserEdit


# Create your views here.
def registration(request):
    context = {}
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(username=email, password=raw_password)
            FavoriteList.objects.create(user=account)
            login(request, account)
            return redirect("users:profile_edit")
        else:
            context['registration_form'] = form
    else:
        form = CustomUserCreationForm()
    return render(request=request, template_name="users/registration.html", context={"register_form": form})


def login_in(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("users:profile")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="users/login.html", context={"login_form": form})


@login_required
def profile(request):
    favorite_list = FavoriteList.objects.get(user=request.user).products.all()
    context = {
        'favorite_list': favorite_list
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login_in')


@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = UserEdit(request.POST, instance=request.user)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect('users:profile')
    else:
        form = UserEdit(instance=request.user)
    return render(request, 'users/changePersonInformation.html', {'form': form})

templates/users/changePersonInformation.html
{% extends 'users/layoutProfile.html' %}

{% block profileContent %}

    <form action="" method="post">
        {% csrf_token %}
        <div class="wrapper-person">
            <div class="person-information">
                <label class="person-label" for="last-name">Имя</label>
                {{ form.first_name }}
            </div>
            <div class="person-information">
                <label class="person-label" for="first-name">Фамилия</label>
                {{ form.last_name }}
            </div>
        </div>
        <div style="margin-top: 30px">
            <div class="person-information" style="display: flex; justify-content: center">
                <div class="person-description-email" style="display: flex; flex-direction: column; align-items: center">
                    <label for="email" class="person-label" style="margin-top: 15px">Почта</label>
                    {{ form.email }}
                </div>
                 <div class="person-description-email" style="display: flex; flex-direction: column; align-items: center">
                    <label for="email" class="person-label" style="margin-top: 15px">Телефон</label>
                    {{ form.phone_no }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a style="display: block; color: black; list-style: none; text-decoration: none; margin-top: 10px" href="{% url 'users:profile' %}">Отмена</a>
    </form>
{% endblock %}

templates/users/layoutProfile.html
{% extends 'main/layout.html' %}

{% block title %}Профиль{% endblock %}

{% block content %}
    <div style="width: 100vw; height: 100vh; background: #FFFFFF">
        <div class="wrapper-profile">
            <div style="text-align: center; margin: 20px 0">
                <img src="../../static/users/images/user.png" alt="avatar" style="width: 50px; height: 50px;"/>
                {% block profileContent %}
                {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends 'main/layout.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div>
        <div class="login-page">
            <h2 style="text-align: center">Авторизация</h2>
            <form method="post">
                {% csrf_token %}
                <div class="login__fields">
                    <label class="login__label" for="username">Имя пользователя: </label>
                    {{ login_form.username }}
                </div>
                <div class="login__fields">
                    <label class=login__labelfor="password">Пароль: </label>
                    {{ login_form.password }}
                </div>
                <button class="btn btn-success login__button" type="submit">Sign up</button>
            </form>
            <a class="login__link-reg" href="{% url 'users:registration' %}">Регистрация</a>
            {% for message in messages %}
                <div class="alert alert-info">Неправильный пароль или логин. Повторите попытку еще</div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/profile.html
{% extends 'users/layoutProfile.html' %}


{% block profileContent %}
    <div class="wrapper-person">
        <div class="person-information">
            <label class="person-label" for="last-name">Имя</label>
            <input disabled class="person-input" type="text" id="last-name" placeholder="Введите имя"
                   value="{{ user.first_name }}">
        </div>
        <div class="person-information">
            <label class="person-label" for="first-name">Фамилия</label>
            <input disabled class="person-input" type="text" id="first-name" placeholder="Введите фамилию"
                   value="{{ user.last_name }}">
        </div>
    </div>
    <div style="margin-top: 30px">
        <div class="person-information">
            <div class="person-description-email" style="display: flex; flex-direction: column; align-items: center">
                <label for="email" class="person-label mailProfile">Почта</label>
                <input disabled type="email" class="person-input" id="email" value="{{ user.email }}"
                       style="width: 480px" placeholder="Введите почту">
            </div>
            <div class="person-description-email" style="display: flex; flex-direction: column; align-items: center">
                <label for="email" class="person-label phoneProfile" style="margin-top: 15px">Номер</label>
                <input disabled type="email" class="person-input" id="email" value="{{ user.phone_no }}"
                       style="width: 480px" placeholder="Введите телефон">
            </div>
        </div>
    </div>
    <div style="text-align: center">
        <a class="btn btn-dark" style="margin-top: 25px"
           href="{% url 'users:logout' %}">Выйти</a>
        <br/>
        <a class="btn btn-secondary" style="margin-top: 15px" href="{% url 'users:profile_edit' %}">Изменить данные</a>
    </div>
    {% if request.user.is_authenticated %}
        {% if request.user.is_superuser %}
            <div>
                <a href="{% url 'main:review_list' %}">
                    Лист со всеми отзывами для редактирования
                </a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/users/registration.html
{% extends 'main/layout.html' %}

{% block content %}
    <div>
        <div class="login-page">
            <h2 style="text-align: center">Регистрация</h2>
            <form method="post">
                {% csrf_token %}
                <div class="login__fields">
                    <label class="login__label" for="username">Имя пользователя: </label>
                    {{ register_form.username }}
                    {{ register_form.errors.username }}
                </div>
                <div class="login__fields">
                    <label class=login__label" for="password1">Введите пароль:</label>
                    {{ register_form.password1 }}
                    <label for="password2">Повторите пароль:</label>
                    {{ register_form.password2 }}
                    {{ register_form.errors.password2 }}
                </div>
                <button class="btn btn-success login__button" type="submit">Зарегистрироваться?</button>
            </form>
            <a class="login__link-reg" href="{% url 'users:login_in' %}">У меня уже есть аккаунт</a>
        </div>
    </div>
{% endblock %}